In [1]:
import pandas as pd
import numpy as np
import category_encoders as ce
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import DataLoader, TensorDataset

## Load Interest Data

In [2]:
interest_data = pd.read_csv('data_total.csv')

## Preprocessing Interest Data

In [3]:
interest_data = interest_data.drop_duplicates(subset=['RESPOND_ID'])

preprocessed_data = interest_data.copy()
preprocessed_data = preprocessed_data.drop(columns=['RESPOND_ID', 'EXAMIN_BEGIN_DE'])
preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,ANSWRR_OC_AREA_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,JN_GJ_TOUR_INTRST_VALUE,JNBK_TOUR_INTRST_VALUE,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE
0,F,50대,서울특별시,300이상500만원 미만,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,약간 커졌다
1,F,50대,서울특별시,500이상700만원 미만,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다
2,F,50대,서울특별시,500이상700만원 미만,약간 커졌다,약간 커졌다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,약간 커졌다
3,F,50대,서울특별시,700만원 이상,예전과 비슷하다,약간 적어졌다,약간 커졌다,약간 적어졌다,약간 적어졌다,약간 적어졌다,예전과 비슷하다,약간 적어졌다,약간 적어졌다,약간 커졌다,약간 커졌다
4,F,50대,서울특별시,500이상700만원 미만,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,예전과 비슷하다
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,F,20대,부산광역시,모름,예전과 비슷하다,예전과 비슷하다,약간 적어졌다,약간 적어졌다,약간 적어졌다,예전과 비슷하다,약간 적어졌다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,많이 커졌다
31295,M,50대,경기도,700만원 이상,예전과 비슷하다,예전과 비슷하다,약간 적어졌다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다
31297,F,40대,경상북도,300만원 미만,약간 커졌다,예전과 비슷하다,약간 커졌다,예전과 비슷하다,약간 커졌다,약간 커졌다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,약간 커졌다,약간 커졌다
31299,M,60대,경기도,700만원 이상,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,예전과 비슷하다,약간 커졌다,예전과 비슷하다,약간 커졌다
31302,F,60대,전라북도,300만원 미만,약간 적어졌다,많이 적어졌다,많이 적어졌다,많이 적어졌다,많이 적어졌다,많이 적어졌다,많이 적어졌다,많이 적어졌다,예전과 비슷하다,약간 적어졌다,예전과 비슷하다

In [4]:

mapping = {
    "많이 적어졌다": 1,
    '약간 적어졌다': 2,
    '예전과 비슷하다': 3,
    '약간 커졌다': 4,
    '많이 커졌다': 5
}

for col in ['SU_TOUR_INTRST_VALUE', 'GG_IC_TOUR_INTRST_VALUE', 'BS_TOUR_INTRST_VALUE', 'CHN_DJ_TOUR_INTRST_VALUE', 'CB_TOUR_INTRST_VALUE', 'GN_US_TOUR_INTRST_VALUE', 'GB_DG_TOUR_INTRST_VALUE', 'JN_GJ_TOUR_INTRST_VALUE', 'JNBK_TOUR_INTRST_VALUE', 'GW_TOUR_INTRST_VALUE', 'JJ_TOUR_INTRST_VALUE']:
    for idx, value in preprocessed_data[col].items():
        # 각 셀의 값에 대한 매핑 수행\
        preprocessed_data.at[idx, col] = mapping.get(str(value), -1)  # 매핑되지 않은 경우 -1로 대체
preprocessed_data = preprocessed_data[preprocessed_data['GG_IC_TOUR_INTRST_VALUE'] != -1]
preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,ANSWRR_OC_AREA_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,JN_GJ_TOUR_INTRST_VALUE,JNBK_TOUR_INTRST_VALUE,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE
0,F,50대,서울특별시,300이상500만원 미만,3,3,3,3,3,4,3,3,3,4,4
1,F,50대,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,3,3
2,F,50대,서울특별시,500이상700만원 미만,4,4,3,3,3,3,3,3,3,4,4
3,F,50대,서울특별시,700만원 이상,3,2,4,2,2,2,3,2,2,4,4
4,F,50대,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,F,20대,부산광역시,모름,3,3,2,2,2,3,2,3,3,3,5
31295,M,50대,경기도,700만원 이상,3,3,2,3,3,3,3,4,3,3,3
31297,F,40대,경상북도,300만원 미만,4,3,4,3,4,4,3,3,4,4,4
31299,M,60대,경기도,700만원 이상,3,3,3,3,3,3,3,3,4,3,4
31302,F,60대,전라북도,300만원 미만,2,1,1,1,1,1,1,1,3,2,3

In [5]:
preprocessed_data['SEXDSTN_FLAG_CD'] = preprocessed_data['SEXDSTN_FLAG_CD'].map({'F': 0, 'M': 1})

preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,ANSWRR_OC_AREA_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,JN_GJ_TOUR_INTRST_VALUE,JNBK_TOUR_INTRST_VALUE,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE
0,0,50대,서울특별시,300이상500만원 미만,3,3,3,3,3,4,3,3,3,4,4
1,0,50대,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,3,3
2,0,50대,서울특별시,500이상700만원 미만,4,4,3,3,3,3,3,3,3,4,4
3,0,50대,서울특별시,700만원 이상,3,2,4,2,2,2,3,2,2,4,4
4,0,50대,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,0,20대,부산광역시,모름,3,3,2,2,2,3,2,3,3,3,5
31295,1,50대,경기도,700만원 이상,3,3,2,3,3,3,3,4,3,3,3
31297,0,40대,경상북도,300만원 미만,4,3,4,3,4,4,3,3,4,4,4
31299,1,60대,경기도,700만원 이상,3,3,3,3,3,3,3,3,4,3,4
31302,0,60대,전라북도,300만원 미만,2,1,1,1,1,1,1,1,3,2,3

In [6]:
age_ordinal_mapping = {
	'20대': 0, 
    '30대': 1,
    '40대': 2,
    '50대': 3,
    '60대': 4,
}

# 데이터 프레임의 모든 열에 대해 오디널 인코딩 적용
preprocessed_data.loc[:, 'AGRDE_FLAG_NM'] = preprocessed_data['AGRDE_FLAG_NM'].map(age_ordinal_mapping)
preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,ANSWRR_OC_AREA_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,JN_GJ_TOUR_INTRST_VALUE,JNBK_TOUR_INTRST_VALUE,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE
0,0,3,서울특별시,300이상500만원 미만,3,3,3,3,3,4,3,3,3,4,4
1,0,3,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,3,3
2,0,3,서울특별시,500이상700만원 미만,4,4,3,3,3,3,3,3,3,4,4
3,0,3,서울특별시,700만원 이상,3,2,4,2,2,2,3,2,2,4,4
4,0,3,서울특별시,500이상700만원 미만,3,3,3,3,3,3,3,3,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,0,0,부산광역시,모름,3,3,2,2,2,3,2,3,3,3,5
31295,1,3,경기도,700만원 이상,3,3,2,3,3,3,3,4,3,3,3
31297,0,2,경상북도,300만원 미만,4,3,4,3,4,4,3,3,4,4,4
31299,1,4,경기도,700만원 이상,3,3,3,3,3,3,3,3,4,3,4
31302,0,4,전라북도,300만원 미만,2,1,1,1,1,1,1,1,3,2,3

In [7]:
korean_to_english_simple = {
    '강원도': 'Gangwon',
    '경기도': 'Gyeonggi',
    '경상남도': 'South Gyeongsang',
    '경상북도': 'North Gyeongsang',
    '광주광역시': 'Gwangju',
    '대구광역시': 'Daegu',
    '대전광역시': 'Daejeon',
    '부산광역시': 'Busan',
    '서울특별시': 'Seoul',
    '울산광역시': 'Ulsan',
    '인천광역시': 'Incheon',
    '전라남도': 'South Jeolla',
    '전라북도': 'North Jeolla',
    '제주도': 'Jeju',
    '충청남도(세종시 포함)': 'South Chungcheong',
    '충청북도': 'North Chungcheong'
}



# 데이터 프레임 내의 한글 지역 이름을 영어로 변경
preprocessed_data.loc[:, 'ANSWRR_OC_AREA_NM'] = preprocessed_data['ANSWRR_OC_AREA_NM'].map(korean_to_english_simple).fillna(preprocessed_data['ANSWRR_OC_AREA_NM'])
    
hash_encoder = ce.HashingEncoder(cols=['ANSWRR_OC_AREA_NM'], n_components=8)  # n_components는 해싱 벡터의 길이 설정
preprocessed_data_hash = hash_encoder.fit_transform(preprocessed_data['ANSWRR_OC_AREA_NM'])

preprocessed_data = pd.concat([preprocessed_data, preprocessed_data_hash], axis=1).drop(columns=['ANSWRR_OC_AREA_NM'])


# 변경된 데이터의 일부를 확인
preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,...,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7
0,0,3,300이상500만원 미만,3,3,3,3,3,4,3,...,4,4,0,0,0,0,0,1,0,0
1,0,3,500이상700만원 미만,3,3,3,3,3,3,3,...,3,3,0,0,0,0,0,1,0,0
2,0,3,500이상700만원 미만,4,4,3,3,3,3,3,...,4,4,0,0,0,0,0,1,0,0
3,0,3,700만원 이상,3,2,4,2,2,2,3,...,4,4,0,0,0,0,0,1,0,0
4,0,3,500이상700만원 미만,3,3,3,3,3,3,3,...,4,3,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,0,0,모름,3,3,2,2,2,3,2,...,3,5,0,0,0,0,0,0,0,1
31295,1,3,700만원 이상,3,3,2,3,3,3,3,...,3,3,0,0,0,0,1,0,0,0
31297,0,2,300만원 미만,4,3,4,3,4,4,3,...,4,4,0,0,0,0,0,0,0,1
31299,1,4,700만원 이상,3,3,3,3,3,3,3,...,3,4,0,0,0,0,1,0,0,0
31302,0,4,300만원 미만,2,1,1,1,1,1,1,...,2,3,1,0,0,0,0,0,0,0

In [8]:
income = {'300만원 미만': 1, '300이상500만원 미만':2, '500이상700만원 미만':3, '700만원 이상':4, '모름':0}

preprocessed_data.loc[:, 'HSHLD_INCOME_DGREE_NM'] = preprocessed_data['HSHLD_INCOME_DGREE_NM'].map(income)

# 변경된 데이터의 일부를 확인
preprocessed_data

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,...,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7
0,0,3,2,3,3,3,3,3,4,3,...,4,4,0,0,0,0,0,1,0,0
1,0,3,3,3,3,3,3,3,3,3,...,3,3,0,0,0,0,0,1,0,0
2,0,3,3,4,4,3,3,3,3,3,...,4,4,0,0,0,0,0,1,0,0
3,0,3,4,3,2,4,2,2,2,3,...,4,4,0,0,0,0,0,1,0,0
4,0,3,3,3,3,3,3,3,3,3,...,4,3,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,0,0,0,3,3,2,2,2,3,2,...,3,5,0,0,0,0,0,0,0,1
31295,1,3,4,3,3,2,3,3,3,3,...,3,3,0,0,0,0,1,0,0,0
31297,0,2,1,4,3,4,3,4,4,3,...,4,4,0,0,0,0,0,0,0,1
31299,1,4,4,3,3,3,3,3,3,3,...,3,4,0,0,0,0,1,0,0,0
31302,0,4,1,2,1,1,1,1,1,1,...,2,3,1,0,0,0,0,0,0,0

In [9]:
def mask_interest_value(df):
	# INTRST_VALUE가 포함된 컬럼 확인
	interest_columns = [col for col in df.columns if 'INTRST_VALUE' in col]

	# 무작위 확률 r로 0으로 만들기
	r = 0.2  # 무작위 확률 설정 (예: 20%)
	for col in interest_columns:
		mask = np.random.rand(len(df)) < r
		df.loc[mask, col] = 0
	return df

In [10]:
preprocessed_data * 1

,SEXDSTN_FLAG_CD,AGRDE_FLAG_NM,HSHLD_INCOME_DGREE_NM,SU_TOUR_INTRST_VALUE,GG_IC_TOUR_INTRST_VALUE,BS_TOUR_INTRST_VALUE,CHN_DJ_TOUR_INTRST_VALUE,CB_TOUR_INTRST_VALUE,GN_US_TOUR_INTRST_VALUE,GB_DG_TOUR_INTRST_VALUE,...,GW_TOUR_INTRST_VALUE,JJ_TOUR_INTRST_VALUE,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7
0,0,3,2,3,3,3,3,3,4,3,...,4,4,0,0,0,0,0,1,0,0
1,0,3,3,3,3,3,3,3,3,3,...,3,3,0,0,0,0,0,1,0,0
2,0,3,3,4,4,3,3,3,3,3,...,4,4,0,0,0,0,0,1,0,0
3,0,3,4,3,2,4,2,2,2,3,...,4,4,0,0,0,0,0,1,0,0
4,0,3,3,3,3,3,3,3,3,3,...,4,3,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31294,0,0,0,3,3,2,2,2,3,2,...,3,5,0,0,0,0,0,0,0,1
31295,1,3,4,3,3,2,3,3,3,3,...,3,3,0,0,0,0,1,0,0,0
31297,0,2,1,4,3,4,3,4,4,3,...,4,4,0,0,0,0,0,0,0,1
31299,1,4,4,3,3,3,3,3,3,3,...,3,4,0,0,0,0,1,0,0,0
31302,0,4,1,2,1,1,1,1,1,1,...,2,3,1,0,0,0,0,0,0,0

In [10]:
preprocessed_data.to_csv("test.csv")